name: bachat_gat_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  websafe_svg: ^3.0.1+6
  fl_chart: ^0.69.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  settings_ui: ^2.0.2
  flutter_settings_ui: ^3.0.1
  curved_navigation_bar: ^1.0.6
  flutter_neumorphic: ^3.2.0
  awesome_dialog: ^3.2.1
  rive: ^0.13.17
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^10.0.1
  syncfusion_flutter_calendar: ^27.2.2
  
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/01.jpg
    - assets/02.jpg
    - assets/03.jpg
    - assets/04.jpg
    - assets/icon/Bellicon.svg
    - assets/icon/Select.svg
    - assets/icon/LoginIcon.svg

  uses-material-design: true
