name: bachat_gat_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Note: Updated to proper SDK range format

dependencies:
  flutter_svg: ^1.0.0
  websafe_svg: ^2.0.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/01.jpg
    - assets/02.jpg
    - assets/03.jpg
    - assets/04.jpg
    - assets/icon/Bellicon.svg
    - assets/icon/Select.svg

  uses-material-design: true
